set(_CATKIN_CURRENT_PACKAGE "serv_msgs")
set(serv_msgs_VERSION "0.0.0")
set(serv_msgs_MAINTAINER "tong <tong@todo.todo>")
set(serv_msgs_PACKAGE_FORMAT "2")
set(serv_msgs_BUILD_DEPENDS "roscpp" "message_generation" "std_msgs")
set(serv_msgs_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs" "message_runtime")
set(serv_msgs_BUILDTOOL_DEPENDS "catkin")
set(serv_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(serv_msgs_EXEC_DEPENDS "roscpp" "std_msgs" "message_runtime")
set(serv_msgs_RUN_DEPENDS "roscpp" "std_msgs" "message_runtime")
set(serv_msgs_TEST_DEPENDS )
set(serv_msgs_DOC_DEPENDS )
set(serv_msgs_URL_WEBSITE "")
set(serv_msgs_URL_BUGTRACKER "")
set(serv_msgs_URL_REPOSITORY "")
set(serv_msgs_DEPRECATED "")